export const IPC_CHANNELS = {
  settingsGet: 'settings:get',
  settingsSave: 'settings:save',
  settingsPickDirectory: 'settings:pick-directory',
  supabaseStatus: 'supabase:status',
  supabaseStartGoogleAuth: 'supabase:start-google-auth',
  supabaseSelectProject: 'supabase:select-project',
  supabaseCreateProject: 'supabase:create-project',
  supabaseSignOut: 'supabase:sign-out',
  googleAuthStatus: 'google:auth-status',
  googleStartAuth: 'google:start-auth',
  googleRevoke: 'google:revoke',
  browserAuthStatus: 'browser-auth:status',
  browserAuthStartLogin: 'browser-auth:start-login',
  browserAuthRevoke: 'browser-auth:revoke',
  analyzeRun: 'analyze:run',
  analyzeManualBug: 'analyze:manual-bug',
  bugsLoadRemote: 'bugs:load-remote',
  bugsWatchRemote: 'bugs:watch-remote',
  bugSetStatus: 'bug:set-status',
  bugAddComment: 'bug:add-comment',
  bugDelete: 'bug:delete',
  bugAnalyzeExternalAgent: 'bug:analyze-external-agent',
  externalAgentProgress: 'external-agent-progress',
  cacheStats: 'cache:stats',
  cacheClear: 'cache:clear',
  appReset: 'app:reset',
  exportExcel: 'export:excel',
  exportBugs: 'export:bugs',
  exportFullData: 'export:full-data',
  dialogOpenExcel: 'dialog:open-excel',
  llmCheckOllama: 'llm:check-ollama',
  llmStartOllama: 'llm:start-ollama',
  hardwareProbe: 'hardware:probe',
  opencodeCheck: 'opencode:check',
  opencodeRepair: 'opencode:repair',
  progress: 'progress',
  log: 'log',
  analysisComplete: 'analysis-complete',
  bugResult: 'bug-result',
  remoteBugsChanged: 'remote-bugs-changed',
} as const

export type IPCChannel = (typeof IPC_CHANNELS)[keyof typeof IPC_CHANNELS]
